import Head from 'next/head';
import Image from 'next/image';

import Profile from '../components/profile';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://github.com/zitadel/zitadel-examples/tree/main/nextjs">Next.js with ZITADEL!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.tsx</code>
        </p>

        <Profile />
      </main>

      <footer className={styles.footer}>
        <a href="https://zitadel.ch" target="_blank" rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/zitadel-logo-dark.svg" alt="Zitadel Logo" height={40} width={147.5} />
          </span>
        </a>
      </footer>
    </div>
  );
}
